global using System;
global using System.Collections.Generic;
global using System.Text;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.AspNetCore.Identity;
global using Solution.Domain.Database.Entities;
global using Microsoft.EntityFrameworkCore;
global using Solution.Domain.Database.Builders;
global using System.Reflection;